# Generated by cpp11: do not edit by hand

cpp_default_device <- function() {
  .Call(`_metalme_cpp_default_device`)
}

cpp_device_info <- function(device_sexp) {
  .Call(`_metalme_cpp_device_info`, device_sexp)
}

cpp_make_library <- function(device_sexp, code) {
  .Call(`_metalme_cpp_make_library`, device_sexp, code)
}

cpp_library_function_names <- function(library_sexp) {
  .Call(`_metalme_cpp_library_function_names`, library_sexp)
}
