# Generated by cpp11: do not edit by hand

cpp_floats <- function(size, fill) {
  .Call(`_metal_cpp_floats`, size, fill)
}

cpp_as_floats <- function(x) {
  .Call(`_metal_cpp_as_floats`, x)
}

cpp_from_floats_lgl <- function(floats_sexp) {
  .Call(`_metal_cpp_from_floats_lgl`, floats_sexp)
}

cpp_from_floats_int <- function(floats_sexp) {
  .Call(`_metal_cpp_from_floats_int`, floats_sexp)
}

cpp_from_floats_dbl <- function(floats_sexp) {
  .Call(`_metal_cpp_from_floats_dbl`, floats_sexp)
}

cpp_default_device <- function() {
  .Call(`_metal_cpp_default_device`)
}

cpp_device_info <- function(device_sexp) {
  .Call(`_metal_cpp_device_info`, device_sexp)
}

cpp_make_library <- function(device_sexp, code) {
  .Call(`_metal_cpp_make_library`, device_sexp, code)
}

cpp_library_function_names <- function(library_sexp) {
  .Call(`_metal_cpp_library_function_names`, library_sexp)
}

cpp_library_function <- function(library_sexp, name) {
  .Call(`_metal_cpp_library_function`, library_sexp, name)
}

cpp_function_info <- function(function_sexp) {
  .Call(`_metal_cpp_function_info`, function_sexp)
}

cpp_buffer <- function(device_sexp, size_dbl) {
  .Call(`_metal_cpp_buffer`, device_sexp, size_dbl)
}

cpp_buffer_size <- function(buffer_sexp) {
  .Call(`_metal_cpp_buffer_size`, buffer_sexp)
}

cpp_buffer_copy_from <- function(src_sexp, buffer_sexp, src_offset, buffer_offset, length) {
  invisible(.Call(`_metal_cpp_buffer_copy_from`, src_sexp, buffer_sexp, src_offset, buffer_offset, length))
}

cpp_buffer_copy_to <- function(buffer_sexp, ptype, buffer_offset, length) {
  .Call(`_metal_cpp_buffer_copy_to`, buffer_sexp, ptype, buffer_offset, length)
}

cpp_buffer_pointer <- function(buffer_sexp) {
  .Call(`_metal_cpp_buffer_pointer`, buffer_sexp)
}

cpp_command_queue <- function(device_sexp) {
  .Call(`_metal_cpp_command_queue`, device_sexp)
}

cpp_compute_pipeline <- function(function_sexp) {
  .Call(`_metal_cpp_compute_pipeline`, function_sexp)
}

cpp_compute_pipeline_execute <- function(pipeline_sexp, commmand_queue_sexp, args) {
  invisible(.Call(`_metal_cpp_compute_pipeline_execute`, pipeline_sexp, commmand_queue_sexp, args))
}
