# Generated by cpp11: do not edit by hand

cpp_default_device <- function() {
  .Call(`_metalme_cpp_default_device`)
}

cpp_device_info <- function(device_sexp) {
  .Call(`_metalme_cpp_device_info`, device_sexp)
}
